### PR TITLE
Initialize repository by transfering benchmark files in NNlib.jl

### PR DESCRIPTION
**Pull request by skyleaworlder**
Transfer benchmark files from NNlib.jl & create a workflow based on .buildkite/pipeline.yml

### PR Checklist

- [ ] Tests are added
- [ ] Documentation, if applicable

### Description

According to the discussion on June 2, 2023, I directly copied the benchmarks from NNlib.jl and created a GitHub workflow here. As a precaution, I create a PR here to verify if these instructions can be successfully migrated to GitHub Actions and run properly on both buildkite and my machine.

### CODE REVIEW

**Comment by skyleaworlder** [comment]
The workflow still failed because there is no "benchmark" folder in our current "main" branch.

So I'll merge this PR to check if benchmarks are able to run successfully.

**Comment by skyleaworlder** [comment]
Too many unnecessary attempts due to my fault. Use squash merge.

**Comment by skyleaworlder** [comment]
image

I run this workflow manually and it can finish successfully.

**But it has to be NOTICED that GitHub Actions only provide "7GB RAM & 2 CPUs"** [(know more here)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). It took approximately 20 minutes to run current benchmarks on my own server with 4 threads. And on GitHub-hosted runner, I use only 1 thread and it took 40 minutes.

As for an organization account, GitHub only provides 2000 minutes Actions quota, which is ample for almost all scenes but is not still enough now, because MetalHead.jl also need to run, especially the DownStream workflow.

So I'll fork this repo to use my own quota (GitHub also provides 2000 minutes for personal account).

**Comment by ToucheSir** [comment]
I think a lot of the time comes from PkgBenchmark.jl tuning the benchmark suite. I don't see a way to stop it doing that, so if it becomes a problem we can consider ditching it for something else.

**Comment by skyleaworlder** [comment]
> I think a lot of the time comes from PkgBenchmark.jl tuning the benchmark suite. I don't see a way to stop it doing that, so if it becomes a problem we can consider ditching it for something else.

Yes, I think so. I've read its code, and there should be no way to jump tuning stage. I created an issue (JuliaCI/PkgBenchmark.jl#150) but at the same time I don't think the maintainers of PkgBenchmark.jl would add this feature, as creating a tune.json file may be they want to see.

Since tuning is from PkgBenchmark.jl, instead of BenchmarkTools.jl, we can use the latter directly.

**Comment by ToucheSir** [comment]
Yes, I was hoping we could save you the effort of doing so but it looks it it'd be worth it. https://github.com/JuliaGPU/CUDA.jl/tree/master/perf might be a good starting point, but if you find anything better feel free to copy that instead.

**Comment by skyleaworlder** [comment]
> Yes, I was hoping we could save you the effort of doing so but it looks it it'd be worth it. https://github.com/JuliaGPU/CUDA.jl/tree/master/perf might be a good starting point, but if you find anything better feel free to copy that instead.

OK. I will have a look at this :)

**Pull request merged**
